r"""
Convert the manuscript's prose from British to American spelling.

IEEE house style is American English. The manuscript was drafted in British
spelling, and the two must not be mixed -- including with the figure labels
and poster text, which are generated by other scripts and would otherwise
disagree with the body text.

What is NOT touched, and why it matters here:

  fenced code blocks   Appendix C is a shell script; its filenames are already
                       American (`normalization.py`) and must not be altered.
  inline `code` spans  same reason: `normalize_capture_confounds`, column
                       names, and file paths are identifiers, not prose.
  URLs and DOIs        a substitution inside a link breaks the link.
  quoted archive text  values such as the licence field literal "Unknown" are
                       quotations of an artefact, not our prose.

Idempotent: every pattern maps a British form to an American one, so a second
run is a no-op.

    python paper/scripts/americanize.py            # rewrite paper.md
    python paper/scripts/americanize.py --check    # report, change nothing
    python paper/scripts/americanize.py --all      # also the figure/poster
                                                   # generators' string labels
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper" / "paper.md"
GENERATORS = [
    ROOT / "paper" / "scripts" / "make_figures.py",
    ROOT / "paper" / "scripts" / "build_poster.py",
]

# British -> American. Order matters only in that longer forms come first.
PAIRS = [
    ("normalisation", "normalization"), ("normalisations", "normalizations"),
    ("normalise", "normalize"), ("normalised", "normalized"),
    ("normalises", "normalizes"), ("normalising", "normalizing"),
    ("generalisation", "generalization"), ("generalisations", "generalizations"),
    ("generalise", "generalize"), ("generalised", "generalized"),
    ("generalises", "generalizes"), ("generalising", "generalizing"),
    ("standardise", "standardize"), ("standardised", "standardized"),
    ("standardisation", "standardization"),
    ("characterise", "characterize"), ("characterised", "characterized"),
    ("characterises", "characterizes"), ("characterising", "characterizing"),
    ("characterisation", "characterization"),
    ("recognise", "recognize"), ("recognised", "recognized"),
    ("recognises", "recognizes"), ("recognising", "recognizing"),
    ("summarise", "summarize"), ("summarised", "summarized"),
    ("summarises", "summarizes"), ("summarising", "summarizing"),
    ("minimise", "minimize"), ("minimised", "minimized"),
    ("maximise", "maximize"), ("maximised", "maximized"),
    ("emphasise", "emphasize"), ("emphasised", "emphasized"),
    ("organise", "organize"), ("organised", "organized"),
    ("prioritise", "prioritize"), ("prioritised", "prioritized"),
    ("utilise", "utilize"), ("utilised", "utilized"),
    ("quantise", "quantize"), ("quantised", "quantized"),
    ("quantisation", "quantization"),
    ("equalise", "equalize"), ("equalised", "equalized"),
    ("penalise", "penalize"), ("penalised", "penalized"),
    ("analyse", "analyze"), ("analysed", "analyzed"), ("analyses", "analyzes"),
    ("colour", "color"), ("colours", "colors"), ("coloured", "colored"),
    ("behaviour", "behavior"), ("behaviours", "behaviors"),
    ("favour", "favor"), ("favours", "favors"), ("favoured", "favored"),
    ("flavour", "flavor"),
    ("labelled", "labeled"), ("labelling", "labeling"),
    ("modelling", "modeling"), ("modelled", "modeled"),
    ("cancelled", "canceled"), ("travelled", "traveled"),
    ("centre", "center"), ("centres", "centers"), ("centred", "centered"),
    ("metre", "meter"), ("metres", "meters"),
    ("artefact", "artifact"), ("artefacts", "artifacts"),
    ("catalogue", "catalog"), ("catalogues", "catalogs"),
    ("licence", "license"), ("licences", "licenses"),
    ("defence", "defense"), ("offence", "offense"),
    ("grey", "gray"), ("greyscale", "grayscale"),
    ("towards", "toward"),
    ("whilst", "while"),
    # second pass: forms the first sweep missed, found by scanning the
    # manuscript for any remaining \w+is(e|ed|es|ing|ation) token
    ("categorise", "categorize"), ("categorised", "categorized"),
    ("categorises", "categorizes"), ("categorising", "categorizing"),
    ("categorisation", "categorization"),
    ("specialise", "specialize"), ("specialised", "specialized"),
    ("specialises", "specializes"), ("specialising", "specializing"),
    ("equalise", "equalize"), ("equalised", "equalized"),
    ("equalises", "equalizes"), ("equalising", "equalizing"),
    ("equalisation", "equalization"),
    ("localise", "localize"), ("localised", "localized"),
    ("localises", "localizes"), ("localising", "localizing"),
    ("localisation", "localization"),
    ("quantises", "quantizes"), ("quantising", "quantizing"),
    ("unnormalised", "unnormalized"), ("unnormalise", "unnormalize"),
    ("synthesise", "synthesize"), ("synthesised", "synthesized"),
    ("synthesises", "synthesizes"), ("synthesising", "synthesizing"),
    ("emphasises", "emphasizes"), ("emphasising", "emphasizing"),
    ("neutralise", "neutralize"), ("neutralised", "neutralized"),
    ("initialise", "initialize"), ("initialised", "initialized"),
    ("initialisation", "initialization"),
    ("digitise", "digitize"), ("digitised", "digitized"),
    ("regularise", "regularize"), ("regularised", "regularized"),
    ("regularisation", "regularization"),
    ("randomise", "randomize"), ("randomised", "randomized"),
    ("randomisation", "randomization"),
    ("finalise", "finalize"), ("finalised", "finalized"),
    ("formalise", "formalize"), ("formalised", "formalized"),
    ("institutionalise", "institutionalize"),
    ("institutionalised", "institutionalized"),
    ("itemise", "itemize"), ("itemised", "itemized"),
    ("hypothesise", "hypothesize"), ("hypothesised", "hypothesized"),
    ("optimise", "optimize"), ("optimised", "optimized"),
    ("optimisation", "optimization"),
    ("visualise", "visualize"), ("visualised", "visualized"),
    ("visualisation", "visualization"),
]

# "analyses" is the plural noun in American English too; only the verb form
# changes. The pair above would wrongly rewrite the noun, so it is removed and
# handled by leaving it alone -- the manuscript uses the noun.
PAIRS = [(b, a) for b, a in PAIRS if b != "analyses"]

# Protected spans, replaced with sentinels before substitution.
PROTECT = [
    re.compile(r"```.*?```", re.S),          # fenced code
    re.compile(r"`[^`\n]*`"),                # inline code
    re.compile(r"https?://\S+"),             # URLs
    re.compile(r"\b[\w./-]+\.(?:py|csv|json|md|pdf|png|jpe?g|zip|tex)\b"),
]


def matchcase(british, american, found):
    if found.isupper():
        return american.upper()
    if found[0].isupper():
        return american[0].upper() + american[1:]
    return american


def convert(text):
    saved, sentinel = [], "\x00PROT{}\x00"
    for pat in PROTECT:
        def stash(m):
            saved.append(m.group(0))
            return sentinel.format(len(saved) - 1)
        text = pat.sub(stash, text)

    counts = {}
    for british, american in PAIRS:
        pat = re.compile(rf"\b{british}\b", re.IGNORECASE)

        def sub(m, b=british, a=american):
            counts[b] = counts.get(b, 0) + 1
            return matchcase(b, a, m.group(0))
        text = pat.sub(sub, text)

    for i, original in enumerate(saved):
        text = text.replace(sentinel.format(i), original)
    return text, counts


def run(path, check):
    original = path.read_text(encoding="utf-8")
    new, counts = convert(original)
    total = sum(counts.values())
    print(f"{path.relative_to(ROOT)}: {total} substitution(s)"
          + (f" across {len(counts)} words" if counts else ""))
    if counts:
        for word, n in sorted(counts.items(), key=lambda kv: -kv[1]):
            print(f"    {word:<18} {n}")
    if not check and new != original:
        path.write_text(new, encoding="utf-8")
    return total


def main():
    check = "--check" in sys.argv
    targets = [PAPER]
    if "--all" in sys.argv:
        targets += [p for p in GENERATORS if p.exists()]
    total = sum(run(p, check) for p in targets)
    print(f"\n{'would change' if check else 'changed'} {total} occurrence(s)")
    if not check and total:
        print("re-run make_figures.py / build_poster.py if their labels changed")


if __name__ == "__main__":
    main()
