r"""
One-shot migration of paper.md to IEEE Access numbering conventions.

Applied 2026-08-13. Kept in the repository because it documents exactly what
was renumbered and can be re-run against the pre-migration backup in
paper/_pre_ieee_backup_20260813/ to reproduce the current source.

What it changes, and why each is required by ieeeaccess.cls:

  sections    "## 7. Results"      -> "## VII. Results"
              "### 7.4 External..." -> "### D. External..."
              IEEEtran numbers first-level sections \Roman and second-level
              \alph.  The numerals are literal text in paper.md, so they are
              rewritten here rather than generated by the renderers.

  tables      "**TABLE XIII.**"    -> "**TABLE 13.**"
              ieeeaccess.cls sets \thetable = \@arabic (Roman is JTEHM-only),
              unlike plain IEEEtran.  This is the single largest diff.
              Appendix tables A.I and B.I continue the sequence as 22 and 23.

  figures     "**Figure 8.**"      -> "**FIGURE 8.**"     (\figurename = FIGURE)
              in-text "Figure 8"   -> "Fig. 8"            (IEEE style: spelled
              out only at the start of a sentence).

  cross-refs  "Section 7.4"        -> "Section VII-D"
              "Table XIII"         -> "Table 13"
              Ranges and lists ("Sections 7.1-7.2", "Tables VII and VIII")
              are rewritten element-wise.

Fenced code blocks are never touched: Appendix C is a shell script whose
comments look exactly like Markdown headings ("# 1. Data pipeline").
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "paper" / "paper.md"

ROMAN = ["", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X",
         "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX",
         "XX", "XXI", "XXII", "XXIII", "XXIV"]
ROMAN_TO_INT = {r: i for i, r in enumerate(ROMAN) if r}

# Appendix tables continue the main Arabic sequence.
APPENDIX_TABLES = {"A.I": 22, "B.I": 23}


def split_code_fences(md):
    """Yield (is_code, text) segments so fenced blocks can be passed through."""
    parts, in_code, buf = [], False, []
    for line in md.split("\n"):
        if line.strip().startswith("```"):
            parts.append((in_code, "\n".join(buf)))
            buf = [line]
            # the fence line itself belongs to the code segment on open,
            # and closes the code segment on close
            if in_code:
                parts.append((True, "\n".join(buf)))
                buf = []
                in_code = False
            else:
                in_code = True
            continue
        buf.append(line)
    parts.append((in_code, "\n".join(buf)))
    return [(c, t) for c, t in parts if t != ""]


def build_section_map(md):
    """{'7': 'VII', '7.4': 'VII-D'} from the numbered headings in the source."""
    smap = {}
    for is_code, seg in split_code_fences(md):
        if is_code:
            continue
        for line in seg.split("\n"):
            m = re.match(r"^##\s+(\d+)\.\s", line)
            if m:
                smap[m.group(1)] = ROMAN[int(m.group(1))]
            m = re.match(r"^###\s+(\d+)\.(\d+)\s", line)
            if m:
                major, minor = m.group(1), m.group(2)
                smap[f"{major}.{minor}"] = f"{ROMAN[int(major)]}-{chr(64 + int(minor))}"
    return smap


def rewrite_headings(seg):
    out = []
    for line in seg.split("\n"):
        m = re.match(r"^##\s+(\d+)\.\s+(.*)$", line)
        if m:
            out.append(f"## {ROMAN[int(m.group(1))]}. {m.group(2)}")
            continue
        m = re.match(r"^###\s+(\d+)\.(\d+)\s+(.*)$", line)
        if m:
            out.append(f"### {chr(64 + int(m.group(2)))}. {m.group(3)}")
            continue
        out.append(line)
    return "\n".join(out)


def rewrite_tables(seg):
    def cap(m):
        numeral = m.group(1)
        n = APPENDIX_TABLES.get(numeral) or ROMAN_TO_INT.get(numeral)
        return f"**TABLE {n}.**" if n else m.group(0)
    seg = re.sub(r"\*\*TABLE\s+([IVXLC]+|[AB]\.I)\.\*\*", cap, seg)

    def ref(m):
        word, body = m.group(1), m.group(2)

        def one(mm):
            numeral = mm.group(0)
            n = APPENDIX_TABLES.get(numeral) or ROMAN_TO_INT.get(numeral)
            return str(n) if n else numeral
        return word + re.sub(r"[AB]\.I\b|[IVXLC]+\b", one, body)
    # a reference is "Table X" optionally continued by ", and, - or to" lists
    seg = re.sub(
        r"\b(Tables?\s+)((?:[AB]\.I|[IVXLC]+)"
        r"(?:\s*(?:,|and|to|–|—|-)\s*(?:[AB]\.I|[IVXLC]+))*)\b",
        ref, seg)
    return seg


def rewrite_sections(seg, smap):
    def ref(m):
        word, body = m.group(1), m.group(2)

        def one(mm):
            return smap.get(mm.group(0), mm.group(0))
        return word + re.sub(r"\d+(?:\.\d+)?", one, body)
    return re.sub(
        r"\b(Sections?\s+)(\d+(?:\.\d+)?"
        r"(?:\s*(?:,|and|to|–|—|-)\s*\d+(?:\.\d+)?)*)",
        ref, seg)


def rewrite_figures(seg):
    # caption label: Figure -> FIGURE
    seg = re.sub(r"(^>\s*)\*\*Figure(\s+\d+\.)\*\*", r"\1**FIGURE\2**",
                 seg, flags=re.M)

    # in-text: abbreviate unless the reference opens a sentence, which is
    # decided from the text *preceding* the match, not from a capture group
    def ref(m):
        before = seg[:m.start()]
        opens_sentence = (
            before == ""
            or re.search(r"(?:^|[.!?:])\s*$", before)      # start of sentence
            or re.search(r"\n\s*$", before)                # start of a line
        )
        if opens_sentence:
            return m.group(0)
        return ("Figs." if m.group(1).endswith("s") else "Fig.") + m.group(2)
    return re.sub(r"\b(Figures|Figure)(\s+\d+)", ref, seg)


def convert(md):
    smap = build_section_map(md)
    out = []
    for is_code, seg in split_code_fences(md):
        if is_code:
            out.append(seg)
            continue
        seg = rewrite_headings(seg)
        seg = rewrite_tables(seg)
        seg = rewrite_sections(seg, smap)
        seg = rewrite_figures(seg)
        out.append(seg)
    return "\n".join(out), smap


def main():
    md = SRC.read_text(encoding="utf-8")
    new, smap = convert(md)

    print(f"section map ({len(smap)} entries):")
    for k in sorted(smap, key=lambda s: [int(x) for x in s.split(".")]):
        print(f"   {k:>5} -> {smap[k]}")

    if "--check" in sys.argv:
        print("\n--check: not written")
        return
    SRC.write_text(new, encoding="utf-8")
    print(f"\nwrote {SRC.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
